services:
- type: web
  name: go-web-app
  env: go
  buildCommand: go build -o main .
  startCommand: ./main
  envVars:
  - key: PORT
    fromService:
      type: web
      name: go-web-app
  - key: DATABASE_URL
    fromService:
      type: pserv
      name: mysql-database
databases:
- name: sistema
  type: mysql